server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sentient?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/com/hoe/sentient/*/*.xml
  type-enums-package: com.hoe.sentient.*.domain.enums
  type-aliases-package: com.hoe.sentient.*.domain.entity
  global-config:
    db-config:
      id-type: input
      field-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

